name: SystemMessages
version: '${project.version}-${git.commit.id.abbrev}'
website: https://robomwm.com
author: RoboMWM
main: com.robomwm.systemmessages.SystemMessages
api-version: '1.16'
softdepend:
  - PurpleIRC
  - GriefPrevention
  - VanishNoPacket
commands:
  setmotd:
    permission: systemmessages.setmotd
    aliases: [ setjoinmotd ]
  setpingmotd:
    permission: systemmessages.setpingmotd

permissions:
  systemmessages.setmotd:
    default: op
  systemmessages.setpingmotd:
    default: op
