name: SystemMessages
version: '${project.version}-${git.commit.id.abbrev}'
website: https://robomwm.com
author: RoboMWM
main: com.robomwm.systemmessages.SystemMessages
api-version: '1.16'
softdepend:
  - PurpleIRC
  - GriefPrevention
